### PR TITLE
v2022.08.0

### PR DESCRIPTION
**Pull request by marodrig**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marodrig** [comment]
@conda-forge-admin, please rerender

**Comment by erogluorhan** [comment]
There is not a v2022.09.0 tag yet in our actual repo. Is this PR correct here?

**Comment by marodrig** [comment]
@erogluorhan This is the v2022.08.0 that hadn't been deployed on conda-forge (it is currently only available on PyPi). I bumped the version up to keep with the current month. Please let me know if this was wrong and I'll update it to the correct version number.

**Comment by erogluorhan** [comment]
> 

WIth the version text "v2022.09.0", it won't be able to find a corresponding tag in our repo, so this will not work. If you create a "v2022.09.0" tag in our repo, then it will create not only conda but also PyPI releases of v2022.09.0. That will leave v2022.08.0 released only at PyPI.

Since there is no actual change from v2022.08.0 so far, I'd suggest making this PR for version "v2022.08.0" so that we could have a version consistency across PyPI and COnda. The only issue with this will be that we will have released our August conda release in September, but I think that'd be okay for this time for version consistency.

ANy thoughts? (cc @anissa111 )

**Comment by anissa111** [comment]
@erogluorhan I agree that this PR should be "v2022.08.0" for consistency.

**Comment by erogluorhan** [comment]
> @erogluorhan I agree that this PR should be "v2022.08.0" for consistency.

Thanks!

@marodrig why didn't we get [this PR](https://github.com/conda-forge/geocat-comp-feedstock/pull/5) to be resolved and merged?

**Comment by marodrig** [comment]
@erogluorhan I lost track of it with all the parallel work I was doing for the other releases. I will pay closer attention next time.

**Comment by erogluorhan** [comment]
> @erogluorhan I lost track of it with all the parallel work I was doing for the other releases. I will pay closer attention next time.

Ok, thanks! Let us keep track of these through opening issues and assigning to you (I already opened those for the upcoming September releases). Let us close this PR and use the one the regro bot created and get it fixed and merged ASAP.

**Comment by marodrig** [comment]
Duplicated PR.

**Pull request closed without merging**
